# Generated by Django 6.0.3 on 2026-03-26 16:07

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_auditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalletransaccion',
            name='descuento_porcentaje',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Porcentaje de descuento (0-100)', max_digits=5),
        ),
        migrations.AddField(
            model_name='detalletransaccion',
            name='margen_linea',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, help_text='Dejar vacío si el producto no tiene vencimiento', null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='precio_venta_distribuidor',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Precio especial para clientes distribuidores/VIP', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='numero_documento',
            field=models.CharField(blank=True, help_text='Auto-generado: FAC-2026-0001', max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='transaccion_origen',
            field=models.ForeignKey(blank=True, help_text='Venta original que origina esta devolución', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devoluciones', to='inventario.transaccion'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='credito_limite',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Monto máximo de crédito autorizado para este cliente', max_digits=12),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='accion',
            field=models.CharField(choices=[('CREATE', 'Creación'), ('UPDATE', 'Actualización'), ('DELETE', 'Eliminación')], max_length=50),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='tipo_documento',
            field=models.CharField(choices=[('COTIZACION', 'Cotización'), ('VENTA', 'Venta Registrada'), ('COMPRA', 'Compra a Proveedor'), ('DEVOLUCION', 'Devolución')], max_length=20),
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('metodo', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TARJETA', 'Tarjeta de Crédito/Débito'), ('TRANSFERENCIA', 'Transferencia Bancaria'), ('MIXTO', 'Pago Mixto')], default='EFECTIVO', max_length=20)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('referencia', models.CharField(blank=True, help_text='Número de voucher, comprobante de transferencia, etc.', max_length=100, null=True)),
                ('fecha_pago', models.DateTimeField(default=django.utils.timezone.now)),
                ('transaccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='inventario.transaccion')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
