# Generated by Django 6.0.3 on 2026-03-26 19:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_detalletransaccion_descuento_porcentaje_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bodega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('ubicacion', models.CharField(blank=True, max_length=255, null=True)),
                ('activa', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='cliente',
            field=models.ForeignKey(blank=True, limit_choices_to={'rol': 'CLIENTE'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compras_cliente', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='numero_documento',
            field=models.CharField(blank=True, help_text='Auto-generado: FAC-2026-0001', max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas_proveedor', to='inventario.proveedor'),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='tipo_documento',
            field=models.CharField(choices=[('COMPRA', 'Compra a Proveedor'), ('VENTA', 'Venta a Cliente'), ('COTIZACION', 'Cotización'), ('DEVOLUCION', 'Devolución'), ('TRANSFERENCIA', 'Transferencia entre Bodegas')], max_length=20),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='bodega',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='transacciones_origen', to='inventario.bodega'),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='bodega_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='transacciones_destino', to='inventario.bodega'),
        ),
        migrations.CreateModel(
            name='InventarioBodega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('bodega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventarios', to='inventario.bodega')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventario_bodegas', to='inventario.producto')),
            ],
            options={
                'unique_together': {('bodega', 'producto')},
            },
        ),
    ]
