# Generated by Django 6.0.3 on 2026-03-26 19:20

from django.db import migrations

def create_bodega(apps, schema_editor):
    Bodega = apps.get_model('inventario', 'Bodega')
    InventarioBodega = apps.get_model('inventario', 'InventarioBodega')
    Producto = apps.get_model('inventario', 'Producto')

    bodega_principal, created = Bodega.objects.get_or_create(
        nombre='Bodega Principal',
        defaults={'ubicacion': 'Sede Central', 'activa': True}
    )

    for producto in Producto.objects.all():
        InventarioBodega.objects.create(
            bodega=bodega_principal,
            producto=producto,
            cantidad=producto.stock_actual
        )

def reverse_bodega(apps, schema_editor):
    Bodega = apps.get_model('inventario', 'Bodega')
    Bodega.objects.filter(nombre='Bodega Principal').delete()

class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_bodega_alter_transaccion_cliente_and_more'),
    ]

    operations = [
        migrations.RunPython(create_bodega, reverse_bodega)
    ]
