# Generated by Django 6.0.3 on 2026-03-26 20:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0007_create_default_bodega'),
    ]

    operations = [
        migrations.CreateModel(
            name='TurnoCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_inicial', models.DecimalField(decimal_places=2, default=0, help_text='Efectivo en caja al inicio del turno', max_digits=12)),
                ('fecha_apertura', models.DateTimeField(auto_now_add=True)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('ABIERTO', 'Abierto'), ('CERRADO', 'Cerrado')], default='ABIERTO', max_length=10)),
                ('total_efectivo_esperado', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_efectivo_declarado', models.DecimalField(decimal_places=2, default=0, help_text='Monto contado físicamente al cierre', max_digits=12)),
                ('diferencia', models.DecimalField(decimal_places=2, default=0, help_text='Positivo=sobrante, Negativo=faltante', max_digits=12)),
                ('observaciones_cierre', models.TextField(blank=True, null=True)),
                ('apertura_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turnos_caja', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_apertura'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('INGRESO', 'Ingreso manual'), ('EGRESO', 'Egreso manual')], max_length=10)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('motivo', models.CharField(max_length=255)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='inventario.turnocaja')),
            ],
        ),
        migrations.AddField(
            model_name='pago',
            name='turno_caja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_del_turno', to='inventario.turnocaja'),
        ),
    ]
