# Generated by Django 6.0.3 on 2026-03-27 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0008_hito7a_caja'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('puede_gestionar_usuarios', models.BooleanField(default=False)),
                ('puede_gestionar_inventario', models.BooleanField(default=True)),
                ('puede_ver_reportes', models.BooleanField(default=False)),
                ('puede_ver_auditoria', models.BooleanField(default=False)),
                ('puede_gestionar_caja', models.BooleanField(default=True)),
                ('puede_vender', models.BooleanField(default=True)),
                ('max_usuarios', models.IntegerField(default=5)),
                ('max_productos', models.IntegerField(default=100)),
            ],
        ),
        migrations.AddField(
            model_name='usuario',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='inventario.plan'),
        ),
    ]
