# Generated by Django 6.0.3 on 2026-03-27 18:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0009_plan_usuario_plan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='puede_gestionar_caja',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='puede_gestionar_inventario',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='puede_gestionar_usuarios',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='puede_vender',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='puede_ver_auditoria',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='puede_ver_reportes',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='plan',
        ),
        migrations.AddField(
            model_name='plan',
            name='modulo_auditoria',
            field=models.BooleanField(default=False, help_text='Habilita Logs de Auditoría'),
        ),
        migrations.AddField(
            model_name='plan',
            name='modulo_caja',
            field=models.BooleanField(default=True, help_text='Habilita Turnos y Movimientos de Caja'),
        ),
        migrations.AddField(
            model_name='plan',
            name='modulo_compras',
            field=models.BooleanField(default=True, help_text='Habilita Compras a Proveedores'),
        ),
        migrations.AddField(
            model_name='plan',
            name='modulo_inventario',
            field=models.BooleanField(default=True, help_text='Habilita Categorías, Productos, Bodegas'),
        ),
        migrations.AddField(
            model_name='plan',
            name='modulo_reportes',
            field=models.BooleanField(default=False, help_text='Habilita Reportes de Rentabilidad y Exportación'),
        ),
        migrations.AddField(
            model_name='plan',
            name='modulo_ventas',
            field=models.BooleanField(default=True, help_text='Habilita Transacciones de Venta y Cotización'),
        ),
        migrations.AlterField(
            model_name='bodega',
            name='nombre',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='plan',
            name='max_productos',
            field=models.IntegerField(default=100, help_text='Máximo de productos permitidos'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='max_usuarios',
            field=models.IntegerField(default=5, help_text='Máximo de usuarios que el cliente puede crear'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='codigo_sku',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='identificacion_fiscal',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='cliente',
            field=models.ForeignKey(blank=True, limit_choices_to={'rol': 'CLIENTE_FINAL'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compras_cliente', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='numero_documento',
            field=models.CharField(blank=True, help_text='Auto-generado: FAC-2026-0001', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('ADMIN', 'Administrador de Empresa'), ('VENDEDOR', 'Vendedor de Empresa'), ('CLIENTE_FINAL', 'Cliente Final (B2C)')], default='CLIENTE_FINAL', max_length=20),
        ),
        migrations.CreateModel(
            name='EmpresaCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=200, unique=True)),
                ('nit', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('activo', models.BooleanField(default=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='empresas', to='inventario.plan')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='bodega',
            name='empresa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bodegas', to='inventario.empresacliente'),
        ),
        migrations.AddField(
            model_name='categoria',
            name='empresa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categorias', to='inventario.empresacliente'),
        ),
        migrations.AddField(
            model_name='producto',
            name='empresa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='inventario.empresacliente'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='empresa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proveedores', to='inventario.empresacliente'),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='empresa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transacciones', to='inventario.empresacliente'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='empleados', to='inventario.empresacliente'),
        ),
        migrations.AlterUniqueTogether(
            name='bodega',
            unique_together={('empresa', 'nombre')},
        ),
        migrations.AlterUniqueTogether(
            name='categoria',
            unique_together={('empresa', 'nombre')},
        ),
        migrations.AlterUniqueTogether(
            name='producto',
            unique_together={('empresa', 'codigo_sku')},
        ),
        migrations.AlterUniqueTogether(
            name='proveedor',
            unique_together={('empresa', 'identificacion_fiscal')},
        ),
        migrations.AlterUniqueTogether(
            name='transaccion',
            unique_together={('empresa', 'numero_documento')},
        ),
    ]
