# Generated by Django 6.0.3 on 2026-03-27 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0010_remove_plan_puede_gestionar_caja_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='modulo_catalogo',
            field=models.BooleanField(default=True, help_text='Habilita el Catálogo de productos'),
        ),
        migrations.AddField(
            model_name='plan',
            name='modulo_clientes',
            field=models.BooleanField(default=True, help_text='Habilita el módulo de Clientes'),
        ),
        migrations.AddField(
            model_name='plan',
            name='modulo_etiquetas',
            field=models.BooleanField(default=True, help_text='Habilita la generación de etiquetas'),
        ),
        migrations.AddField(
            model_name='plan',
            name='modulo_usuarios',
            field=models.BooleanField(default=True, help_text='Habilita la gestión de Personal (Usuarios)'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='modulo_compras',
            field=models.BooleanField(default=True, help_text='Habilita Compras a Proveedores y Proveedores'),
        ),
    ]
