# Generated by Django 6.0.3 on 2026-04-10 19:27

from django.db import migrations

def make_javier_admin(apps, schema_editor):
    Usuario = apps.get_model('inventario', 'Usuario')
    try:
        javier = Usuario.objects.get(username='javier')
        javier.rol = 'ADMIN'
        javier.is_superuser = True
        javier.is_staff = True
        javier.save()
    except Usuario.DoesNotExist:
        pass

class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0011_plan_modulo_catalogo_plan_modulo_clientes_and_more'),
    ]

    operations = [
        migrations.RunPython(make_javier_admin),
    ]
